import { CaseData, OperatorAlert, OperatorUser } from './types';

export const CURRENT_OPERATOR: OperatorUser = {
  id: 'op-994',
  name: 'Ananya Roy',
  email: 'ananya.roy@sukoon.ai',
  role: 'Senior Crisis Specialist & Operator',
  badgeId: 'CR-8821',
  shift: 'Day Operations (08:00 - 18:00)',
};

export const INITIAL_CASES: CaseData[] = [
  {
    id: '1287',
    sessionCode: 'Session #1287',
    svi: 82,
    riskLevel: 'Critical',
    riskTrend: 'Rising',
    status: 'New',
    userType: 'Anonymous',
    language: 'English (US)',
    inputType: 'Voice & Text',
    startedAt: 'Today 14:10',
    lastActivity: '2 min ago',
    escalationStatus: 'Immediate Safety Concern',
    assignedOperator: 'Unassigned',
    detectedIndicators: ['Immediate Danger', 'Fear', 'Intimidation', 'Emotional Distress'],
    recommendedActions: ['Emergency Helpline', 'Police Support', 'Immediate Human Follow-up', 'Discreet Evacuation Shelter'],
    voiceAnalysis: {
      available: true,
      speechActivity: 'High vocal tremor detected (74%)',
      pausePattern: 'Frequent erratic hesitations (>3.2s)',
      pitchVariation: 'Elevated pitch variability in distress frequencies',
      confidence: '88%',
      emotionalIndicators: ['Acute Panic', 'Hyperventilation cues', 'Suppressed speech volume'],
      notes: 'Acoustic cues indicate heightened physiological arousal and restricted vocal output consistent with high immediate stress.',
    },
    history: [
      { time: '14:10', timestamp: Date.now() - 1200000, svi: 45, category: 'Moderate', event: 'Session initiated via voice input' },
      { time: '14:14', timestamp: Date.now() - 960000, svi: 62, category: 'High', event: 'Disclosure of active domestic intimidation' },
      { time: '14:18', timestamp: Date.now() - 720000, svi: 78, category: 'Critical', event: 'Immediate physical barrier / confinement mentioned' },
      { time: '14:22', timestamp: Date.now() - 480000, svi: 82, category: 'Critical', event: 'Rapid silence following sudden distress vocalisation' },
    ],
    transcript: [
      {
        id: 'msg-1287-1',
        sender: 'ai',
        text: 'Welcome to Sukoon AI. You are in a confidential, safe space. How are you feeling right now?',
        time: '14:10',
        inputType: 'text',
      },
      {
        id: 'msg-1287-2',
        sender: 'user',
        text: "I don't know where else to turn... he came back earlier than expected and he is banging on the locked door. I locked myself in the bathroom.",
        time: '14:12',
        inputType: 'voice',
        audioDuration: '8.4s',
      },
      {
        id: 'msg-1287-3',
        sender: 'ai',
        text: 'I hear the urgency and fear in your voice. Your physical safety is the absolute priority right now. Are you able to safely contact emergency local authorities, or do you have a secure secondary exit?',
        time: '14:13',
        inputType: 'text',
      },
      {
        id: 'msg-1287-4',
        sender: 'user',
        text: 'He said if I call the police it will be much worse. I am terrified. My hands are shaking so much I can barely speak.',
        time: '14:16',
        inputType: 'voice',
        audioDuration: '6.1s',
      },
      {
        id: 'msg-1287-5',
        sender: 'ai',
        text: 'Please stay low and keep your device completely silent. You do not have to carry this alone. If you cannot speak aloud, you can text emergency services (such as 988 or 911/112) or use silent emergency signaling.',
        time: '14:18',
        inputType: 'text',
      },
      {
        id: 'msg-1287-6',
        sender: 'user',
        text: 'I hear him trying the door handle again. Please help me.',
        time: '14:20',
        inputType: 'voice',
        audioDuration: '4.2s',
      },
    ],
    notes: [],
  },
  {
    id: '1286',
    sessionCode: 'Session #1286',
    svi: 68,
    riskLevel: 'High',
    riskTrend: 'Stable',
    status: 'Acknowledged',
    userType: 'Account Session',
    maskedUserId: 'usr_7721_enc',
    language: 'English (UK)',
    inputType: 'Text',
    startedAt: 'Today 13:45',
    lastActivity: '6 min ago',
    escalationStatus: 'High Distress Trigger',
    assignedOperator: 'Ananya Roy',
    acknowledgedBy: 'Ananya Roy',
    acknowledgedAt: 'Today 14:02',
    detectedIndicators: ['Hopelessness', 'Anxiety', 'Social Isolation', 'Low Mood'],
    recommendedActions: ['Counselling', 'Medical Support', 'Human Follow-up', 'Crisis Helpline'],
    voiceAnalysis: {
      available: false,
      notes: 'No voice analysis available for this session.',
    },
    history: [
      { time: '13:45', timestamp: Date.now() - 3600000, svi: 38, category: 'Moderate', event: 'Session started via encrypted text' },
      { time: '13:58', timestamp: Date.now() - 2820000, svi: 54, category: 'High', event: 'Severe chronic fatigue & isolation disclosure' },
      { time: '14:15', timestamp: Date.now() - 1800000, svi: 68, category: 'High', event: 'Persistent self-blame and hopelessness expressed' },
    ],
    transcript: [
      {
        id: 'msg-1286-1',
        sender: 'ai',
        text: 'Welcome back. I am here whenever you are ready to share.',
        time: '13:45',
        inputType: 'text',
      },
      {
        id: 'msg-1286-2',
        sender: 'user',
        text: "I haven't left my room in four days. Everything feels completely pointless and heavy. I feel like a burden to everyone around me.",
        time: '13:52',
        inputType: 'text',
      },
      {
        id: 'msg-1286-3',
        sender: 'ai',
        text: 'Thank you for reaching out and telling me this. Carrying that deep emotional heaviness alone is exhausting. You are not a burden, and what you are feeling right now is valid. Can you tell me if you have eaten or had water today?',
        time: '13:53',
        inputType: 'text',
      },
      {
        id: 'msg-1286-4',
        sender: 'user',
        text: "Just a little water. I just don't have the strength to face tomorrow.",
        time: '14:01',
        inputType: 'text',
      },
    ],
    notes: [
      {
        id: 'note-1286-1',
        operatorName: 'Ananya Roy',
        operatorRole: 'Senior Crisis Specialist',
        timestamp: 'Today 14:02',
        createdAt: Date.now() - 2400000,
        content: 'Acknowledged case. SVI at 68. Validated emotional distress patterns. Encouraging gentle somatic anchoring and monitoring for acute escalation.',
      },
    ],
  },
  {
    id: '1285',
    sessionCode: 'Session #1285',
    svi: 88,
    riskLevel: 'Critical',
    riskTrend: 'Rising',
    status: 'Acknowledged',
    userType: 'Anonymous',
    language: 'English (US)',
    inputType: 'Voice & Text',
    startedAt: 'Today 12:30',
    lastActivity: '18 min ago',
    escalationStatus: 'Rapid SVI Increase',
    assignedOperator: 'Ananya Roy',
    acknowledgedBy: 'Ananya Roy',
    acknowledgedAt: 'Today 12:45',
    detectedIndicators: ['Hopelessness', 'Immediate Danger', 'Severe Depression', 'Social Isolation'],
    recommendedActions: ['Emergency Helpline', 'Medical Support', 'Human Follow-up', 'Crisis Counselling'],
    voiceAnalysis: {
      available: true,
      speechActivity: 'Flat acoustic affect with intermittent sobbing cues',
      pausePattern: 'Prolonged silences (>5.0s)',
      pitchVariation: 'Sub-baseline pitch compression (monotone emotional exhaustion)',
      confidence: '92%',
      emotionalIndicators: ['Severe Depressive Exhaustion', 'Acoustic withdrawal', 'Somatic distress'],
      notes: 'Voice profile displays pronounced acoustic suppression and lengthened inter-word pauses.',
    },
    history: [
      { time: '12:30', timestamp: Date.now() - 7200000, svi: 52, category: 'High', event: 'Session initiated' },
      { time: '12:40', timestamp: Date.now() - 6600000, svi: 75, category: 'High', event: 'Active crisis ideation statement' },
      { time: '12:44', timestamp: Date.now() - 6360000, svi: 88, category: 'Critical', event: 'Critical threshold crossed (SVI 88)' },
    ],
    transcript: [
      {
        id: 'msg-1285-1',
        sender: 'ai',
        text: 'Hello. I am right here with you. Take all the time you need.',
        time: '12:30',
        inputType: 'text',
      },
      {
        id: 'msg-1285-2',
        sender: 'user',
        text: 'I think I am done fighting. I just wanted someone to listen one last time.',
        time: '12:38',
        inputType: 'voice',
        audioDuration: '5.8s',
      },
      {
        id: 'msg-1285-3',
        sender: 'ai',
        text: 'I hear how much pain you are holding, and I am staying right here with you. Your life has immense dignity, and you do not have to go through this darkness alone. Please stay with me. Can you take one slow, deep breath with me right now?',
        time: '12:39',
        inputType: 'text',
      },
    ],
    notes: [
      {
        id: 'note-1285-1',
        operatorName: 'Ananya Roy',
        operatorRole: 'Senior Crisis Specialist',
        timestamp: 'Today 12:45',
        createdAt: Date.now() - 6300000,
        content: 'Active critical case. Direct crisis de-escalation protocol provided in assistant responses. Connected with regional 988 dispatch monitoring team.',
      },
    ],
  },
  {
    id: '1284',
    sessionCode: 'Session #1284',
    svi: 42,
    riskLevel: 'Moderate',
    riskTrend: 'Decreasing',
    status: 'Resolved',
    userType: 'Account Session',
    maskedUserId: 'usr_3914_enc',
    language: 'English (US)',
    inputType: 'Text',
    startedAt: 'Today 11:15',
    lastActivity: '1 hour ago',
    escalationStatus: 'None',
    assignedOperator: 'Dev Patel',
    acknowledgedBy: 'Dev Patel',
    acknowledgedAt: 'Today 11:22',
    resolvedBy: 'Dev Patel',
    resolvedAt: 'Today 12:10',
    resolutionNote: 'User successfully completed guided breathing sequence and scheduled a follow-up check-in with their designated university counsellor.',
    detectedIndicators: ['Anxiety', 'Emotional Distress'],
    recommendedActions: ['Counselling', 'Human Follow-up'],
    voiceAnalysis: {
      available: false,
      notes: 'No voice analysis available for this session.',
    },
    history: [
      { time: '11:15', timestamp: Date.now() - 11700000, svi: 52, category: 'High', event: 'Session started with exam anxiety' },
      { time: '11:35', timestamp: Date.now() - 10500000, svi: 46, category: 'Moderate', event: 'Engaged with cognitive grounding prompt' },
      { time: '12:05', timestamp: Date.now() - 8700000, svi: 42, category: 'Moderate', event: 'Resolution confirmed by operator' },
    ],
    transcript: [
      {
        id: 'msg-1284-1',
        sender: 'ai',
        text: 'Welcome. What is on your mind today?',
        time: '11:15',
        inputType: 'text',
      },
      {
        id: 'msg-1284-2',
        sender: 'user',
        text: 'I was having a massive panic attack about my academic evaluations. My heart was racing.',
        time: '11:18',
        inputType: 'text',
      },
      {
        id: 'msg-1284-3',
        sender: 'ai',
        text: 'Take a soft pause. Let us place both feet flat on the floor together. Inhale gently for 4 counts, hold for 4, and exhale softly for 6.',
        time: '11:19',
        inputType: 'text',
      },
      {
        id: 'msg-1284-4',
        sender: 'user',
        text: 'That helped a lot. My chest feels much lighter now. Thank you.',
        time: '12:04',
        inputType: 'text',
      },
    ],
    notes: [
      {
        id: 'note-1284-1',
        operatorName: 'Dev Patel',
        operatorRole: 'Counsellor',
        timestamp: 'Today 11:22',
        createdAt: Date.now() - 11280000,
        content: 'Monitored somatic grounding responses.',
      },
    ],
  },
  {
    id: '1283',
    sessionCode: 'Session #1283',
    svi: 18,
    riskLevel: 'Low',
    riskTrend: 'Stable',
    status: 'Resolved',
    userType: 'Anonymous',
    language: 'English (US)',
    inputType: 'Text',
    startedAt: 'Today 10:00',
    lastActivity: '2 hours ago',
    escalationStatus: 'None',
    assignedOperator: 'Ananya Roy',
    acknowledgedBy: 'Ananya Roy',
    acknowledgedAt: 'Today 10:10',
    resolvedBy: 'Ananya Roy',
    resolvedAt: 'Today 10:45',
    resolutionNote: 'General mindfulness journaling and emotional debriefing completed. User closed session peacefully.',
    detectedIndicators: ['Low Mood'],
    recommendedActions: ['Counselling'],
    voiceAnalysis: {
      available: false,
      notes: 'No voice analysis available for this session.',
    },
    history: [
      { time: '10:00', timestamp: Date.now() - 16200000, svi: 22, category: 'Low', event: 'Session started' },
      { time: '10:30', timestamp: Date.now() - 14400000, svi: 18, category: 'Low', event: 'Journal reflection concluded' },
    ],
    transcript: [
      {
        id: 'msg-1283-1',
        sender: 'ai',
        text: 'Welcome to Sukoon AI. Take all the time you need.',
        time: '10:00',
        inputType: 'text',
      },
      {
        id: 'msg-1283-2',
        sender: 'user',
        text: 'Just wanted to reflect on a difficult conversation I had yesterday with a colleague.',
        time: '10:04',
        inputType: 'text',
      },
    ],
    notes: [],
  },
  {
    id: '1282',
    sessionCode: 'Session #1282',
    svi: 74,
    riskLevel: 'High',
    riskTrend: 'Rising',
    status: 'New',
    userType: 'Anonymous',
    language: 'English (US)',
    inputType: 'Voice & Text',
    startedAt: 'Today 09:30',
    lastActivity: '25 min ago',
    escalationStatus: 'Emotional Distress Spike',
    assignedOperator: 'Unassigned',
    detectedIndicators: ['Fear', 'Emotional Distress', 'Intimidation'],
    recommendedActions: ['Legal Aid', 'Counselling', 'Human Follow-up', 'Police Support'],
    voiceAnalysis: {
      available: true,
      speechActivity: 'Rapid pace with breathlessness',
      pausePattern: 'Sub-second abrupt interruptions',
      pitchVariation: 'High frequency variance (>140Hz shift)',
      confidence: '85%',
      emotionalIndicators: ['Severe Agitation', 'Hyperarousal'],
      notes: 'Voice profile indicates acute agitation and fight-or-flight vocal response patterns.',
    },
    history: [
      { time: '09:30', timestamp: Date.now() - 18000000, svi: 48, category: 'Moderate', event: 'Session started' },
      { time: '09:42', timestamp: Date.now() - 17280000, svi: 66, category: 'High', event: 'Reported stalker intimidation outside residence' },
      { time: '09:50', timestamp: Date.now() - 16800000, svi: 74, category: 'High', event: 'High risk escalation triggered' },
    ],
    transcript: [
      {
        id: 'msg-1282-1',
        sender: 'ai',
        text: 'Welcome. You are safe to speak freely.',
        time: '09:30',
        inputType: 'text',
      },
      {
        id: 'msg-1282-2',
        sender: 'user',
        text: 'The person who has been harassing me is standing across the street from my apartment right now.',
        time: '09:42',
        inputType: 'voice',
        audioDuration: '5.2s',
      },
    ],
    notes: [],
  },
  {
    id: '1281',
    sessionCode: 'Session #1281',
    svi: 32,
    riskLevel: 'Moderate',
    riskTrend: 'Stable',
    status: 'New',
    userType: 'Account Session',
    maskedUserId: 'usr_1022_enc',
    language: 'English',
    inputType: 'Text',
    startedAt: 'Today 08:50',
    lastActivity: '42 min ago',
    escalationStatus: 'None',
    assignedOperator: 'Unassigned',
    detectedIndicators: ['Anxiety', 'Social Isolation'],
    recommendedActions: ['Counselling', 'Human Follow-up'],
    voiceAnalysis: {
      available: false,
      notes: 'No voice analysis available for this session.',
    },
    history: [
      { time: '08:50', timestamp: Date.now() - 20400000, svi: 34, category: 'Moderate', event: 'Session started' },
      { time: '09:10', timestamp: Date.now() - 19200000, svi: 32, category: 'Moderate', event: 'Moderate anxiety debrief' },
    ],
    transcript: [
      {
        id: 'msg-1281-1',
        sender: 'ai',
        text: 'Good morning. How can I support you today?',
        time: '08:50',
        inputType: 'text',
      },
      {
        id: 'msg-1281-2',
        sender: 'user',
        text: 'Feeling quite isolated living in a new city and struggling to form connections.',
        time: '08:55',
        inputType: 'text',
      },
    ],
    notes: [],
  },
];

export const INITIAL_ALERTS: OperatorAlert[] = [
  {
    id: 'alt-1',
    caseId: '1287',
    sessionCode: 'Session #1287',
    title: 'Critical Risk Detected — Immediate Safety Concern',
    description: 'Active domestic threat and confinement disclosed. SVI 82 with elevated voice panic markers.',
    severity: 'Critical',
    timestamp: '2 min ago',
    createdAt: Date.now() - 120000,
    isAcknowledged: false,
    triggerReason: 'SVI > 75 & Immediate Danger indicator',
  },
  {
    id: 'alt-2',
    caseId: '1285',
    sessionCode: 'Session #1285',
    title: 'Rapid SVI Increase (+36 points in 14 min)',
    description: 'Rapid transition from high to critical threshold (SVI 88). Sustained acoustic suppression cues.',
    severity: 'Critical',
    timestamp: '18 min ago',
    createdAt: Date.now() - 1080000,
    isAcknowledged: true,
    triggerReason: 'Delta SVI > 30 / 15m',
  },
  {
    id: 'alt-3',
    caseId: '1282',
    sessionCode: 'Session #1282',
    title: 'High Distress Trigger — Stalker Proximity',
    description: 'User reported physical intimidation outside dwelling. SVI increased to 74.',
    severity: 'High',
    timestamp: '25 min ago',
    createdAt: Date.now() - 1500000,
    isAcknowledged: false,
    triggerReason: 'Safety proximity disclosure',
  },
  {
    id: 'alt-4',
    caseId: '1287',
    sessionCode: 'Session #1287',
    title: 'Silence After High-Risk Disclosure (>180s)',
    description: 'No subsequent input received after user sent urgent plea for physical safety.',
    severity: 'Warning',
    timestamp: '3 min ago',
    createdAt: Date.now() - 180000,
    isAcknowledged: false,
    triggerReason: 'Abrupt audio termination after critical statement',
  },
];

export const SVI_DISTRIBUTION = [
  { range: 'Low (0–25)', count: 24, percent: '38%', color: '#10b981', category: 'Low' },
  { range: 'Moderate (26–50)', count: 21, percent: '33%', color: '#f59e0b', category: 'Moderate' },
  { range: 'High (51–75)', count: 12, percent: '19%', color: '#f97316', category: 'High' },
  { range: 'Critical (76–100)', count: 6, percent: '10%', color: '#ef4444', category: 'Critical' },
];

export const SVI_TREND_DATA = [
  { time: '08:00', avgSvi: 34, highRiskCount: 2, criticalCount: 0 },
  { time: '09:00', avgSvi: 41, highRiskCount: 4, criticalCount: 1 },
  { time: '10:00', avgSvi: 38, highRiskCount: 3, criticalCount: 0 },
  { time: '11:00', avgSvi: 45, highRiskCount: 5, criticalCount: 1 },
  { time: '12:00', avgSvi: 58, highRiskCount: 8, criticalCount: 2 },
  { time: '13:00', avgSvi: 52, highRiskCount: 6, criticalCount: 1 },
  { time: '14:00', avgSvi: 64, highRiskCount: 9, criticalCount: 3 },
];

export const REPORTS_DATA = {
  totalSessions: 63,
  activeSessions: 18,
  resolvedToday: 45,
  escalationsCount: 11,
  averageResponseTime: '1.4 min',
  voiceAnalysisCount: 28,
  riskBreakdown: [
    { name: 'Low (0–25)', value: 24, fill: '#10b981' },
    { name: 'Moderate (26–50)', value: 21, fill: '#f59e0b' },
    { name: 'High (51–75)', value: 12, fill: '#f97316' },
    { name: 'Critical (76–100)', value: 6, fill: '#ef4444' },
  ],
  hourlyVolume: [
    { hour: '06:00', total: 4, highRisk: 0 },
    { hour: '08:00', total: 9, highRisk: 2 },
    { hour: '10:00', total: 14, highRisk: 3 },
    { hour: '12:00', total: 22, highRisk: 8 },
    { hour: '14:00', total: 18, highRisk: 9 },
    { hour: '16:00', total: 11, highRisk: 4 },
  ],
  actionDistribution: [
    { action: 'Human Follow-up', count: 19 },
    { action: 'Emergency Helpline', count: 14 },
    { action: 'Counselling Referral', count: 28 },
    { action: 'Legal Aid Advisory', count: 8 },
    { action: 'Police Support Connection', count: 5 },
  ],
};
